//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_StokTakip.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullaniciRolleri
    {
        public int ID { get; set; }
        public Nullable<int> KullanıcıID { get; set; }
        public Nullable<int> RolID { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Roller Roller { get; set; }
    }
}
