//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_StokTakip.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urunler()
        {
            this.Satislar = new HashSet<Satislar>();
            this.Satislar1 = new HashSet<Satislar>();
            this.Sepet = new HashSet<Sepet>();
            this.Sepet1 = new HashSet<Sepet>();
            this.MarkaListesi = new List<SelectListItem>();
            this.MarkaListesi.Insert(0, new SelectListItem { Text = "Önce Kategori Değeri Seçilmelidir", Value = "" });
        }

        public int ID { get; set; }
        [Required(ErrorMessage="Kategori Alanı boş geçilemez")]
        [Display(Name = "Kategori")]
        public Nullable<int> KategoriID { get; set; }
        [Required(ErrorMessage = "Marka Alanı boş geçilemez")]
        [Display(Name = "Marka")]
        public Nullable<int> MarkaID { get; set; }
        [Required(ErrorMessage = "Ürün Adı Alanı boş geçilemez")]
        [Display(Name = "Ürün Adı")]
        public string UrunAdi { get; set; }
        [Required(ErrorMessage = "Barkod Alanı boş geçilemez")]
        [Display(Name = "Barkod Alanı")]
        public string BarkodNo { get; set; }
        [Required(ErrorMessage = "Alış Fiyatı Alanı boş geçilemez")]
        [Display(Name = "Alış Fiyatı")]
        public decimal? AlisFiyati { get; set; }
        [Required(ErrorMessage = "Satış Fiyatı Alanı boş geçilemez")]
        [Display(Name = "Satış Fiyatı")]
        public decimal SatisFiyati { get; set; }
        [Required(ErrorMessage = "Miktar Alanı boş geçilemez")]
        [Display(Name = "Miktar")]
        public decimal Miktarı { get; set; }
        [Required(ErrorMessage = "KDV Alanı boş geçilemez")]
        [Range(0, 100, ErrorMessage = "0-100 arası rakam girilmelidir.")]
        [Display(Name = "KDV")]
        public int? KDV { get; set; }
        [Required(ErrorMessage = "Birim Alanı boş geçilemez")]
     
        public Nullable<int> BirimID { get; set; }
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Tarih Alanı boş geçilemez")]
        public Nullable<System.DateTime> Tarih { get; set; }
        [Required(ErrorMessage = "Açıklama Alanı boş geçilemez")]
        [Display(Name ="Açıklama")]
        public string Aciklama { get; set; }

        public virtual Birimler Birimler { get; set; }
        public virtual Kategoriler Kategoriler { get; set; }
        public virtual Markalar Markalar { get; set; }
        public virtual Markalar Markalar1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satislar> Satislar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satislar> Satislar1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sepet> Sepet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sepet> Sepet1 { get; set; }

        public List<SelectListItem> KategoriListesi {get;set;}
        public List<SelectListItem> MarkaListesi { get; set; }
        public List<SelectListItem> BirimListesi { get; set; }

    }
}
